"use client";
import React, { useState, useEffect, useRef, useMemo } from "react";
import ExamTable from "../table/ExamTable";
import {
  LoadingWrapper,
  SkeletonPageContent,
  LoadingSpinner,
} from "../ui/SkeletonLoader";
import {
  FaPlus,
  FaTimes,
  FaSave,
  FaExclamationTriangle,
  FaClipboardList,
  FaLock,
  FaSearch,
} from "react-icons/fa";
import { ToastContainer, useToast } from "../ui/Toast";
import api from "@/lib/api";
import { usePermissions, getPermissionMessage } from "../../hooks/usePermissions";
import { useRouter } from "next/navigation";

const ExamManagement = () => {
  const { canCreate, canEdit, canDelete, canReorder, role } = usePermissions();
  const router = useRouter();
  const [showAddForm, setShowAddForm] = useState(false);
  const [isDataLoading, setIsDataLoading] = useState(false);
  const [isFormLoading, setIsFormLoading] = useState(false);
  const [exams, setExams] = useState([]);
  const [error, setError] = useState(null);
  const [editingExam, setEditingExam] = useState(null);
  const [formData, setFormData] = useState({
    name: "",
    status: "active",
    orderNumber: "",
    image: "",
    description: ["", "", "", ""], // Exactly 4 items
  });
  const [formError, setFormError] = useState(null);
  const { toasts, removeToast, success, error: showError } = useToast();
  const isFetchingRef = useRef(false);
  const [metaFilter, setMetaFilter] = useState("all"); // all, filled, notFilled
  const [searchQuery, setSearchQuery] = useState("");

  // Fetch exams from API using Axios
  const fetchExams = async () => {
    if (isFetchingRef.current) return; // prevent overlapping fetches
    isFetchingRef.current = true;
    try {
      setIsDataLoading(true);
      setError(null);
      // Fetch all exams (active and inactive) to show correct status
      const response = await api.get(`/exam?status=all&metaStatus=${metaFilter}`);

      if (response.data?.success) {
        setExams(response.data.data || []);
      } else {
        setError(response.data?.message || "Failed to fetch exams");
      }
    } catch (error) {
      console.error("Error fetching exams:", error);
      const errorMessage =
        error?.response?.data?.message ||
        "Failed to fetch exams. Please check your connection.";
      setError(errorMessage);
    } finally {
      setIsDataLoading(false);
      isFetchingRef.current = false;
    }
  };

  // Load exams when filter changes
  useEffect(() => {
    fetchExams();
  }, [metaFilter]);

  // Client-side filtering for search
  const filteredExams = useMemo(() => {
    return exams.filter((exam) => {
      const matchesSearch = exam.name
        .toLowerCase()
        .includes(searchQuery.toLowerCase());
      return matchesSearch;
    });
  }, [exams, searchQuery]);

  // Set orderNumber when editing (not needed for adding since it's auto-generated)
  useEffect(() => {
    if (editingExam) {
      setFormData(prev => ({
        ...prev,
        orderNumber: editingExam.orderNumber?.toString() || "",
      }));
    }
  }, [editingExam]);

  const handleAddExam = async (e) => {
    e.preventDefault();

    // Check permissions
    if (!canCreate) {
      showError(getPermissionMessage("create", role));
      return;
    }

    if (!formData.name.trim()) {
      setFormError("Please enter an exam name");
      return;
    }

    try {
      setIsFormLoading(true);
      setFormError(null);

      const payload = {
        name: formData.name.trim(),
        status: formData.status,
        image: formData.image.trim(),
        description: formData.description.filter(d => d.trim() !== ""),
        // orderNumber is auto-generated by the API, so we don't send it
      };

      console.log("Submitting payload:", payload);
      const response = await api.post("/exam", payload);

      if (response.data.success) {
        // Add the new exam to the list
        setExams((prevExams) => [...prevExams, response.data.data]);
        success(`Exam "${formData.name}" added successfully!`);
        // Reset form
        setFormData({
          name: "",
          status: "active",
          orderNumber: "",
          image: "",
          description: ["", "", "", ""],
        });
        setEditingExam(null);
        setShowAddForm(false);
      } else {
        setFormError(response.data.message || "Failed to add exam");
        showError(response.data.message || "Failed to add exam");
      }
    } catch (error) {
      console.error("Error adding exam:", error);
      const errorMessage =
        error.response?.data?.message ||
        "Failed to add exam. Please try again.";
      setFormError(errorMessage);
      showError(errorMessage);
    } finally {
      setIsFormLoading(false);
    }
  };

  const handleFormChange = (e, index = null) => {
    const { name, value } = e.target;
    if (name === "description" && index !== null) {
      setFormData((prev) => {
        const newDesc = [...prev.description];
        newDesc[index] = value;
        return { ...prev, description: newDesc };
      });
    } else {
      setFormData((prev) => ({
        ...prev,
        [name]: value,
      }));
    }
    setFormError(null);
  };

  const handleCancelForm = () => {
    setFormData({
      name: "",
      status: "active",
      orderNumber: "",
      image: "",
      description: ["", "", "", ""],
    });
    setFormError(null);
    setEditingExam(null);
    setShowAddForm(false);
  };

  const handleEditExam = (exam) => {
    // Check permissions
    if (!canEdit) {
      showError(getPermissionMessage("edit", role));
      return;
    }
    setEditingExam(exam);
    setFormData({
      name: exam.name || "",
      status: exam.status || "active",
      orderNumber: exam.orderNumber?.toString() || "",
      image: exam.image || "",
      description: (exam.description && exam.description.length > 0)
        ? [...exam.description, "", "", "", ""].slice(0, 4)
        : ["", "", "", ""],
    });
    setShowAddForm(true);
    setFormError(null);
  };

  const handleUpdateExam = async (e) => {
    e.preventDefault();

    // Check permissions
    if (!canEdit) {
      showError(getPermissionMessage("edit", role));
      return;
    }

    if (!formData.name.trim()) {
      setFormError("Please enter an exam name");
      return;
    }

    try {
      setIsFormLoading(true);
      setFormError(null);

      const payload = {
        name: formData.name.trim(),
        status: formData.status,
        image: formData.image.trim(),
        description: formData.description.filter(d => d.trim() !== ""),
      };

      // Add orderNumber if provided
      if (formData.orderNumber && formData.orderNumber.trim()) {
        payload.orderNumber = parseInt(formData.orderNumber);
      }

      console.log("Updating payload:", payload);
      const response = await api.put(`/exam/${editingExam._id}`, payload);

      if (response.data.success) {
        // Update the exam in the list
        setExams((prevExams) =>
          prevExams.map((e) => (e._id === editingExam._id ? response.data.data : e))
        );
        success("Exam updated successfully!");
        handleCancelForm();
      } else {
        setFormError(response.data.message || "Failed to update exam");
        showError(response.data.message || "Failed to update exam");
      }
    } catch (error) {
      console.error("Error updating exam:", error);
      const errorMessage =
        error.response?.data?.message ||
        "Failed to update exam. Please try again.";
      setFormError(errorMessage);
      showError(errorMessage);
    } finally {
      setIsFormLoading(false);
    }
  };

  const handleDeleteExam = async (exam) => {
    // Check permissions
    if (!canDelete) {
      showError(getPermissionMessage("delete", role));
      return;
    }

    if (window.confirm(`Are you sure you want to delete "${exam.name}"?`)) {
      try {
        setIsFormLoading(true);
        setError(null);

        const response = await api.delete(`/exam/${exam._id}`);

        if (response.data.success) {
          // Remove the exam from the list
          setExams((prevExams) => prevExams.filter((e) => e._id !== exam._id));
          success(`Exam "${exam.name}" deleted successfully!`);
        } else {
          setError(response.data.message || "Failed to delete exam");
          showError(response.data.message || "Failed to delete exam");
        }
      } catch (error) {
        console.error("Error deleting exam:", error);
        const errorMessage =
          error.response?.data?.message ||
          "Failed to delete exam. Please try again.";
        setError(errorMessage);
        showError(errorMessage);
      } finally {
        setIsFormLoading(false);
      }
    }
  };

  const handleManageInfo = (exam) => {
    router.push(`/admin/exam-info/${exam._id}`);
  };

  const handleToggleStatus = async (exam) => {
    const currentStatus = exam.status || "active";
    const newStatus = currentStatus === "active" ? "inactive" : "active";
    const action = newStatus === "inactive" ? "deactivate" : "activate";

    if (
      window.confirm(
        `Are you sure you want to ${action} "${exam.name}"? All its children will also be ${action}d.`
      )
    ) {
      try {
        setIsFormLoading(true);
        setError(null);

        const response = await api.patch(`/exam/${exam._id}`, {
          status: newStatus,
        });

        if (response.data.success) {
          // Refetch exams to get updated status from database
          await fetchExams();
          success(
            `Exam "${exam.name}" and all children ${action}d successfully!`
          );
        } else {
          setError(response.data.message || `Failed to ${action} exam`);
          showError(response.data.message || `Failed to ${action} exam`);
        }
      } catch (error) {
        console.error(`Error ${action}ing exam:`, error);
        const errorMessage =
          error.response?.data?.message ||
          `Failed to ${action} exam. Please try again.`;
        setError(errorMessage);
        showError(errorMessage);
      } finally {
        setIsFormLoading(false);
      }
    }
  };

  return (
    <>
      <ToastContainer toasts={toasts} removeToast={removeToast} />
      <div className="space-y-6">
        {/* Page Header */}
        <div className="bg-gradient-to-r from-blue-50 via-indigo-50 to-purple-50 rounded-lg border border-gray-200 p-4 shadow-sm">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
            <div>
              <h1 className="text-xl font-semibold text-gray-900 mb-1">
                Exam Management
              </h1>
              <p className="text-xs text-gray-600">
                Manage and organize your exams, create new assessments, and track exam performance across your educational platform.
              </p>
            </div>
            {canCreate ? (
              <button
                onClick={() => setShowAddForm(true)}
                className="px-2 py-1 bg-[#0056FF] hover:bg-[#0044CC] text-white rounded-lg text-xs font-medium transition-colors"
              >
                Add New Exam
              </button>
            ) : (
              <button
                disabled
                title={getPermissionMessage("create", role)}
                className="px-2 py-1 bg-gray-300 text-gray-500 rounded-lg text-xs font-medium cursor-not-allowed"
              >
                Add New Exam
              </button>
            )}
          </div>
        </div>

        {/* Add/Edit Exam Form */}
        {showAddForm && (
          <div className="bg-white rounded-lg border border-gray-200 p-6 shadow-sm">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-xl font-semibold text-gray-900">
                {editingExam ? "Edit Exam" : "Add New Exam"}
              </h2>
              <button
                onClick={handleCancelForm}
                className="text-gray-400 hover:text-gray-600 hover:bg-gray-100 p-2 rounded-lg transition-colors"
                disabled={isFormLoading}
              >
                <FaTimes className="w-4 h-4" />
              </button>
            </div>

            <form onSubmit={editingExam ? handleUpdateExam : handleAddExam} className="space-y-4">
              {/* Form Error Display */}
              {formError && (
                <div className="bg-red-50 border border-red-200 rounded-lg p-4">
                  <div className="flex items-center gap-2">
                    <div className="w-2 h-2 bg-red-500 rounded-full"></div>
                    <p className="text-sm font-medium text-red-800">
                      {formError}
                    </p>
                  </div>
                </div>
              )}

              <div className={`grid grid-cols-1 ${editingExam ? 'md:grid-cols-3' : 'md:grid-cols-2'} gap-4`}>
                {/* Exam Name */}
                <div className="space-y-2">
                  <label
                    htmlFor="name"
                    className="block text-sm font-medium text-gray-700"
                  >
                    Exam Name <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    id="name"
                    name="name"
                    value={formData.name}
                    onChange={handleFormChange}
                    placeholder="Enter exam name (e.g., JEE Main 2024)"
                    className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm placeholder-gray-400 transition-all"
                    required
                    disabled={isFormLoading}
                  />
                </div>

                {/* Order Number - Only show when editing */}
                {editingExam && (
                  <div className="space-y-2">
                    <label
                      htmlFor="orderNumber"
                      className="block text-sm font-medium text-gray-700"
                    >
                      Order Number
                    </label>
                    <input
                      type="number"
                      id="orderNumber"
                      name="orderNumber"
                      value={formData.orderNumber}
                      onChange={handleFormChange}
                      placeholder="Enter order number"
                      min="1"
                      className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm placeholder-gray-400 transition-all"
                      disabled={isFormLoading}
                    />
                  </div>
                )}

                {/* Status */}
                <div className="space-y-2">
                  <label
                    htmlFor="status"
                    className="block text-sm font-medium text-gray-700"
                  >
                    Status
                  </label>
                  <select
                    id="status"
                    name="status"
                    value={formData.status}
                    onChange={handleFormChange}
                    className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm transition-all"
                    disabled={isFormLoading}
                  >
                    <option value="active">Active</option>
                    <option value="inactive">Inactive</option>
                    <option value="draft">Draft</option>
                  </select>
                </div>
              </div>

              {/* Image URL */}
              <div className="space-y-2">
                <label
                  htmlFor="image"
                  className="block text-sm font-medium text-gray-700"
                >
                  Card Image URL (Optional)
                </label>
                <input
                  type="text"
                  id="image"
                  name="image"
                  value={formData.image}
                  onChange={handleFormChange}
                  placeholder="Enter image URL (e.g., https://example.com/image.png)"
                  className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm placeholder-gray-400 transition-all"
                  disabled={isFormLoading}
                />
              </div>

              {/* Description Items */}
              <div className="space-y-2">
                <label className="block text-sm font-medium text-gray-700">
                  Card Descriptions (Max 4 items - Optional)
                </label>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {formData.description.map((item, index) => (
                    <div key={index} className="relative">
                      <input
                        type="text"
                        name="description"
                        value={item}
                        onChange={(e) => handleFormChange(e, index)}
                        placeholder={`Description item ${index + 1}`}
                        className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm placeholder-gray-400 transition-all"
                        disabled={isFormLoading}
                      />
                    </div>
                  ))}
                </div>
              </div>

              {/* Form Actions */}
              <div className="flex flex-col sm:flex-row justify-end gap-3 pt-4 border-t border-gray-200">
                <button
                  type="button"
                  onClick={handleCancelForm}
                  className="px-3 py-1.5 text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-lg text-sm font-medium transition-colors"
                  disabled={isFormLoading}
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                  disabled={isFormLoading}
                >
                  {isFormLoading ? (
                    <>
                      <LoadingSpinner size="small" />
                      <span>{editingExam ? "Updating..." : "Adding Exam..."}</span>
                    </>
                  ) : (
                    <>
                      <FaSave className="w-4 h-4" />
                      <span>{editingExam ? "Update Exam" : "Add Exam"}</span>
                    </>
                  )}
                </button>
              </div>
            </form>
          </div>
        )}

        {/* Content Area */}
        <div className="bg-white rounded-lg border border-gray-200 overflow-hidden shadow-sm">
          <div className="px-4 py-3 border-b border-gray-200 bg-gray-50">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div>
                <h2 className="text-xl font-semibold text-gray-900">
                  Exams List
                </h2>
                <p className="text-sm text-gray-600 mt-1">
                  Manage your exams, view details, and perform actions
                </p>
              </div>
              <div className="flex flex-wrap items-center gap-3">
                {/* Search Input */}
                <div className="relative min-w-[200px] sm:min-w-[240px]">
                  <input
                    type="text"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    placeholder="Search exams..."
                    className="w-full pl-9 pr-8 py-1.5 bg-white border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                  />
                  <FaSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 w-3.5 h-3.5" />
                  {searchQuery && (
                    <button
                      onClick={() => setSearchQuery("")}
                      className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 transition-colors"
                    >
                      <FaTimes className="w-3 h-3" />
                    </button>
                  )}
                </div>

                <div className="flex items-center gap-2">
                  <label className="text-[10px] font-bold text-gray-400 uppercase tracking-wider whitespace-nowrap">Meta Status:</label>
                  <select
                    value={metaFilter}
                    onChange={(e) => setMetaFilter(e.target.value)}
                    className="px-3 py-1.5 bg-white border border-gray-200 rounded-lg text-xs font-medium focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                  >
                    <option value="all">All Items</option>
                    <option value="filled">Meta Filled</option>
                    <option value="notFilled">Meta Not Filled</option>
                  </select>
                </div>
              </div>
            </div>
          </div>

          <div className="p-2">
            {isDataLoading ? (
              <div className="flex items-center justify-center py-12">
                <div className="text-center">
                  <LoadingSpinner size="medium" />
                  <p className="text-sm text-gray-500 mt-3">Loading exams...</p>
                </div>
              </div>
            ) : filteredExams.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-12 text-center">
                <div className="p-4 bg-gray-100 rounded-full mb-4">
                  <FaClipboardList className="w-8 h-8 text-gray-400" />
                </div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">
                  No Exams Found
                </h3>
                <p className="text-sm text-gray-500 mb-4 max-w-sm">
                  {searchQuery
                    ? "No exams match your search criteria."
                    : "You haven't created any exams yet. Click the \"Add New Exam\" button to get started."}
                </p>
                {searchQuery ? (
                  <button
                    onClick={() => setSearchQuery("")}
                    className="px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm font-medium transition-colors"
                  >
                    Clear Search
                  </button>
                ) : canCreate ? (
                  <button
                    onClick={() => setShowAddForm(true)}
                    className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg text-sm font-semibold transition-all duration-200 flex items-center gap-2"
                  >
                    <FaPlus className="w-4 h-4" />
                    Create Your First Exam
                  </button>
                ) : (
                  <div className="px-4 py-2 bg-gray-100 text-gray-500 rounded-lg text-sm font-medium flex items-center gap-2">
                    <FaLock className="w-4 h-4" />
                    <span>{getPermissionMessage("create", role)}</span>
                  </div>
                )}
              </div>
            ) : (
              <ExamTable
                exams={filteredExams}
                onEdit={handleEditExam}
                onDelete={handleDeleteExam}
                onToggleStatus={handleToggleStatus}
                onManageInfo={handleManageInfo}
              />
            )}
          </div>
        </div>
      </div>
    </>
  );
};

export default ExamManagement;
