"use client";
import React, { useState, useEffect, useRef, useMemo } from "react";
import ExamTable from "../table/ExamTable";
import {
  LoadingWrapper,
  SkeletonPageContent,
  LoadingSpinner,
} from "../ui/SkeletonLoader";
import {
  FaPlus,
  FaTimes,
  FaSave,
  FaExclamationTriangle,
  FaClipboardList,
  FaLock,
  FaSearch,
  FaGripVertical,
  FaCheck,
} from "react-icons/fa";
import { ToastContainer, useToast } from "../ui/Toast";
import StatusCascadeModal from "../ui/StatusCascadeModal";
import api from "@/lib/api";
import { getExamListCache, setExamListCache } from "@/lib/examListCache";
import { invalidateListCachesFrom } from "@/lib/listCacheInvalidation";
import { usePermissions, getPermissionMessage } from "../../hooks/usePermissions";
import { useRouter } from "next/navigation";
import { IoFilterOutline } from "react-icons/io5";
import { useFilterPersistence } from "../../hooks/useFilterPersistence";
import PaginationBar from "../ui/PaginationBar";

const ExamManagement = () => {
  const { canCreate, canEdit, canDelete, canReorder, role } = usePermissions();
  const router = useRouter();
  const [filterState, setFilterState] = useFilterPersistence("exam", {
    metaFilter: "all",
    searchQuery: "",
  });
  const { page, limit, metaFilter, searchQuery } = filterState;

  const [showAddForm, setShowAddForm] = useState(false);
  const [isDataLoading, setIsDataLoading] = useState(false);
  const [isFormLoading, setIsFormLoading] = useState(false);
  const [exams, setExams] = useState([]);
  const [pagination, setPagination] = useState({
    total: 0,
    totalPages: 0,
    hasNextPage: false,
    hasPrevPage: false,
  });
  const [error, setError] = useState(null);
  const [editingExam, setEditingExam] = useState(null);
  const [formData, setFormData] = useState({
    name: "",
    status: "active",
    orderNumber: "",
    image: "",
    description: ["", "", "", ""], // Exactly 4 items
  });
  const [formError, setFormError] = useState(null);
  const { toasts, removeToast, success, error: showError } = useToast();
  const isFetchingRef = useRef(false);
  const [isReorderMode, setIsReorderMode] = useState(false);
  const [reorderDraft, setReorderDraft] = useState(null);
  const [cascadeModalOpen, setCascadeModalOpen] = useState(false);
  const [cascadeItem, setCascadeItem] = useState(null);

  // Fetch exams from API (with pagination; no list cache when paginated)
  const fetchExams = React.useCallback(async () => {
    if (isFetchingRef.current) return;
    isFetchingRef.current = true;
    try {
      setIsDataLoading(true);
      setError(null);
      const response = await api.get(
        `/exam?status=all&metaStatus=${metaFilter}&page=${page}&limit=${limit}`
      );

      if (response.data?.success) {
        const data = response.data.data || [];
        setExams(data);
        const pag = response.data?.pagination;
        if (pag) {
          setPagination({
            total: pag.total ?? 0,
            totalPages: pag.totalPages ?? 0,
            hasNextPage: !!pag.hasNextPage,
            hasPrevPage: !!pag.hasPrevPage,
          });
        }
        setExamListCache(data, metaFilter);
      } else {
        setError(response.data?.message || "Failed to fetch exams");
      }
    } catch (error) {
      console.error("Error fetching exams:", error);
      const errorMessage =
        error?.response?.data?.message ||
        "Failed to fetch exams. Please check your connection.";
      setError(errorMessage);
    } finally {
      setIsDataLoading(false);
      isFetchingRef.current = false;
    }
  }, [metaFilter, page, limit]);

  // Load exams when filter or pagination changes
  useEffect(() => {
    fetchExams();
  }, [fetchExams]);

  // Client-side filtering for search (within current page)
  const filteredExams = useMemo(() => {
    if (!searchQuery.trim()) return exams;
    const q = searchQuery.toLowerCase().trim();
    return exams.filter((exam) => exam.name?.toLowerCase().includes(q));
  }, [exams, searchQuery]);

  // Set orderNumber when editing (not needed for adding since it's auto-generated)
  useEffect(() => {
    if (editingExam) {
      setFormData(prev => ({
        ...prev,
        orderNumber: editingExam.orderNumber?.toString() || "",
      }));
    }
  }, [editingExam]);

  const handleAddExam = async (e) => {
    e.preventDefault();

    // Check permissions
    if (!canCreate) {
      showError(getPermissionMessage("create", role));
      return;
    }

    if (!formData.name.trim()) {
      setFormError("Please enter an exam name");
      return;
    }

    try {
      setIsFormLoading(true);
      setFormError(null);

      const payload = {
        name: formData.name.trim(),
        status: formData.status,
        image: formData.image.trim(),
        description: formData.description.filter(d => d.trim() !== ""),
        // orderNumber is auto-generated by the API, so we don't send it
      };

      console.log("Submitting payload:", payload);
      const response = await api.post("/exam", payload);

      if (response.data.success) {
        invalidateListCachesFrom("exam");
        await fetchExams();
        success(`Exam "${formData.name}" added successfully!`);
        // Reset form
        setFormData({
          name: "",
          status: "active",
          orderNumber: "",
          image: "",
          description: ["", "", "", ""],
        });
        setEditingExam(null);
        setShowAddForm(false);
      } else {
        setFormError(response.data.message || "Failed to add exam");
        showError(response.data.message || "Failed to add exam");
      }
    } catch (error) {
      console.error("Error adding exam:", error);
      const errorMessage =
        error.response?.data?.message ||
        "Failed to add exam. Please try again.";
      setFormError(errorMessage);
      showError(errorMessage);
    } finally {
      setIsFormLoading(false);
    }
  };

  const handleFormChange = (e, index = null) => {
    const { name, value } = e.target;
    if (name === "description" && index !== null) {
      setFormData((prev) => {
        const newDesc = [...prev.description];
        newDesc[index] = value;
        return { ...prev, description: newDesc };
      });
    } else {
      setFormData((prev) => ({
        ...prev,
        [name]: value,
      }));
    }
    setFormError(null);
  };

  const handleCancelForm = () => {
    setFormData({
      name: "",
      status: "active",
      orderNumber: "",
      image: "",
      description: ["", "", "", ""],
    });
    setFormError(null);
    setEditingExam(null);
    setShowAddForm(false);
  };

  const handleEditExam = (exam) => {
    // Check permissions
    if (!canEdit) {
      showError(getPermissionMessage("edit", role));
      return;
    }
    setEditingExam(exam);
    setFormData({
      name: exam.name || "",
      status: exam.status || "active",
      orderNumber: exam.orderNumber?.toString() || "",
      image: exam.image || "",
      description: (exam.description && exam.description.length > 0)
        ? [...exam.description, "", "", "", ""].slice(0, 4)
        : ["", "", "", ""],
    });
    setShowAddForm(true);
    setFormError(null);
  };

  const handleUpdateExam = async (e) => {
    e.preventDefault();

    // Check permissions
    if (!canEdit) {
      showError(getPermissionMessage("edit", role));
      return;
    }

    if (!formData.name.trim()) {
      setFormError("Please enter an exam name");
      return;
    }

    try {
      setIsFormLoading(true);
      setFormError(null);

      const payload = {
        name: formData.name.trim(),
        status: formData.status,
        image: formData.image.trim(),
        description: formData.description.filter(d => d.trim() !== ""),
      };

      // Add orderNumber if provided
      if (formData.orderNumber && formData.orderNumber.trim()) {
        payload.orderNumber = parseInt(formData.orderNumber);
      }

      console.log("Updating payload:", payload);
      const response = await api.put(`/exam/${editingExam._id}`, payload);

      if (response.data.success) {
        invalidateListCachesFrom("exam");
        await fetchExams();
        success("Exam updated successfully!");
        handleCancelForm();
      } else {
        setFormError(response.data.message || "Failed to update exam");
        showError(response.data.message || "Failed to update exam");
      }
    } catch (error) {
      console.error("Error updating exam:", error);
      const errorMessage =
        error.response?.data?.message ||
        "Failed to update exam. Please try again.";
      setFormError(errorMessage);
      showError(errorMessage);
    } finally {
      setIsFormLoading(false);
    }
  };

  const handleDeleteExam = async (exam) => {
    // Check permissions
    if (!canDelete) {
      showError(getPermissionMessage("delete", role));
      return;
    }

    if (window.confirm(`Are you sure you want to delete "${exam.name}"?`)) {
      try {
        setIsFormLoading(true);
        setError(null);

        const response = await api.delete(`/exam/${exam._id}`);

        if (response.data.success) {
          invalidateListCachesFrom("exam");
          await fetchExams();
          success(`Exam "${exam.name}" deleted successfully!`);
        } else {
          setError(response.data.message || "Failed to delete exam");
          showError(response.data.message || "Failed to delete exam");
        }
      } catch (error) {
        console.error("Error deleting exam:", error);
        const errorMessage =
          error.response?.data?.message ||
          "Failed to delete exam. Please try again.";
        setError(errorMessage);
        showError(errorMessage);
      } finally {
        setIsFormLoading(false);
      }
    }
  };

  const handleManageInfo = (exam) => {
    router.push(`/admin/exam-info/${exam._id}`);
  };

  const saveReorderForExams = async (newOrderedExams) => {
    const payload = {
      exams: newOrderedExams.map((exam, i) => ({
        id: exam._id,
        orderNumber: i + 1,
      })),
    };
    const response = await api.post("/exam/reorder", payload);
    if (!response.data?.success) {
      throw new Error(response.data?.message || "Failed to reorder exams");
    }
  };

  const handleReorderDraft = (newOrderedExams) => {
    setReorderDraft(newOrderedExams);
  };

  const handleDoneReorder = async () => {
    if (!canReorder) {
      showError(getPermissionMessage("reorder", role));
      return;
    }
    if (reorderDraft === null) {
      setIsReorderMode(false);
      return;
    }
    try {
      setIsFormLoading(true);
      setError(null);
      await saveReorderForExams(reorderDraft);
      invalidateListCachesFrom("exam");
      await fetchExams();
      setReorderDraft(null);
      setIsReorderMode(false);
      success("Exam order updated successfully.");
    } catch (err) {
      const msg = err?.response?.data?.message || err?.message || "Failed to reorder exams. Please try again.";
      showError(msg);
    } finally {
      setIsFormLoading(false);
    }
  };

  const handleToggleStatus = (exam) => {
    setCascadeItem(exam);
    setCascadeModalOpen(true);
  };

  const handleCascadeConfirm = async (newStatus, cascadeMode) => {
    if (!cascadeItem) return;
    const action = newStatus === "inactive" ? "deactivate" : "activate";
    try {
      setIsFormLoading(true);
      setError(null);
      const response = await api.patch(`/exam/${cascadeItem._id}`, {
        status: newStatus,
        cascadeMode: cascadeMode || "respect_manual",
      });
      if (response.data.success) {
        invalidateListCachesFrom("exam");
        await fetchExams();
        success(
          `Exam "${cascadeItem.name}" and children ${action}d successfully!`
        );
        setCascadeModalOpen(false);
        setCascadeItem(null);
      } else {
        setError(response.data.message || `Failed to ${action} exam`);
        showError(response.data.message || `Failed to ${action} exam`);
      }
    } catch (error) {
      console.error(`Error ${action}ing exam:`, error);
      const errorMessage =
        error.response?.data?.message ||
        `Failed to ${action} exam. Please try again.`;
      setError(errorMessage);
      showError(errorMessage);
    } finally {
      setIsFormLoading(false);
    }
  };

  return (
    <>
      <ToastContainer toasts={toasts} removeToast={removeToast} />
      <StatusCascadeModal
        open={cascadeModalOpen}
        onClose={() => { setCascadeModalOpen(false); setCascadeItem(null); }}
        levelLabel="Exam"
        itemName={cascadeItem?.name}
        currentStatus={cascadeItem?.status || "active"}
        onConfirm={handleCascadeConfirm}
        loading={isFormLoading}
      />
      <div className="space-y-6">
        {/* Page Header */}
        <div className="bg-gradient-to-r from-blue-50 via-indigo-50 to-purple-50 rounded-lg border border-gray-200 p-4 shadow-sm">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
            <div>
              <h1 className="text-xl font-semibold text-gray-900 mb-1">
                Exam Management
              </h1>
              <p className="text-xs text-gray-600">
                Manage and organize your exams, create new assessments, and track exam performance across your educational platform.
              </p>
            </div>
            {canCreate ? (
              <button
                onClick={() => setShowAddForm(true)}
                className="px-2 py-1 bg-[#0056FF] hover:bg-[#0044CC] text-white rounded-lg text-xs font-medium transition-colors"
              >
                Add New Exam
              </button>
            ) : (
              <button
                disabled
                title={getPermissionMessage("create", role)}
                className="px-2 py-1 bg-gray-300 text-gray-500 rounded-lg text-xs font-medium cursor-not-allowed"
              >
                Add New Exam
              </button>
            )}
          </div>
        </div>

        {/* Add/Edit Exam Form */}
        {showAddForm && (
          <div className="bg-white rounded-lg border border-gray-200 p-6 shadow-sm">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-xl font-semibold text-gray-900">
                {editingExam ? "Edit Exam" : "Add New Exam"}
              </h2>
              <button
                onClick={handleCancelForm}
                className="text-gray-400 hover:text-gray-600 hover:bg-gray-100 p-2 rounded-lg transition-colors"
                disabled={isFormLoading}
              >
                <FaTimes className="w-4 h-4" />
              </button>
            </div>

            <form onSubmit={editingExam ? handleUpdateExam : handleAddExam} className="space-y-4">
              {/* Form Error Display */}
              {formError && (
                <div className="bg-red-50 border border-red-200 rounded-lg p-4">
                  <div className="flex items-center gap-2">
                    <div className="w-2 h-2 bg-red-500 rounded-full"></div>
                    <p className="text-sm font-medium text-red-800">
                      {formError}
                    </p>
                  </div>
                </div>
              )}

              <div className={`grid grid-cols-1 ${editingExam ? 'md:grid-cols-3' : 'md:grid-cols-2'} gap-4`}>
                {/* Exam Name */}
                <div className="space-y-2">
                  <label
                    htmlFor="name"
                    className="block text-sm font-medium text-gray-700"
                  >
                    Exam Name <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    id="name"
                    name="name"
                    value={formData.name}
                    onChange={handleFormChange}
                    placeholder="Enter exam name (e.g., JEE Main 2024)"
                    className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm placeholder-gray-400 transition-all"
                    required
                    disabled={isFormLoading}
                  />
                </div>

                {/* Order Number - Only show when editing */}
                {editingExam && (
                  <div className="space-y-2">
                    <label
                      htmlFor="orderNumber"
                      className="block text-sm font-medium text-gray-700"
                    >
                      Order Number
                    </label>
                    <input
                      type="number"
                      id="orderNumber"
                      name="orderNumber"
                      value={formData.orderNumber}
                      onChange={handleFormChange}
                      placeholder="Enter order number"
                      min="1"
                      className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm placeholder-gray-400 transition-all"
                      disabled={isFormLoading}
                    />
                  </div>
                )}

                {/* Status */}
                <div className="space-y-2">
                  <label
                    htmlFor="status"
                    className="block text-sm font-medium text-gray-700"
                  >
                    Status
                  </label>
                  <select
                    id="status"
                    name="status"
                    value={formData.status}
                    onChange={handleFormChange}
                    className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm transition-all"
                    disabled={isFormLoading}
                  >
                    <option value="active">Active</option>
                    <option value="inactive">Inactive</option>
                    <option value="draft">Draft</option>
                  </select>
                </div>
              </div>

              {/* Image URL */}
              <div className="space-y-2">
                <label
                  htmlFor="image"
                  className="block text-sm font-medium text-gray-700"
                >
                  Card Image URL (Optional)
                </label>
                <input
                  type="text"
                  id="image"
                  name="image"
                  value={formData.image}
                  onChange={handleFormChange}
                  placeholder="Enter image URL (e.g., https://example.com/image.png)"
                  className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm placeholder-gray-400 transition-all"
                  disabled={isFormLoading}
                />
              </div>

              {/* Description Items */}
              <div className="space-y-2">
                <label className="block text-sm font-medium text-gray-700">
                  Card Descriptions (Max 4 items - Optional)
                </label>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {formData.description.map((item, index) => (
                    <div key={index} className="relative">
                      <input
                        type="text"
                        name="description"
                        value={item}
                        onChange={(e) => handleFormChange(e, index)}
                        placeholder={`Description item ${index + 1}`}
                        className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm placeholder-gray-400 transition-all"
                        disabled={isFormLoading}
                      />
                    </div>
                  ))}
                </div>
              </div>

              {/* Form Actions */}
              <div className="flex flex-col sm:flex-row justify-end gap-3 pt-4 border-t border-gray-200">
                <button
                  type="button"
                  onClick={handleCancelForm}
                  className="px-3 py-1.5 text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-lg text-sm font-medium transition-colors"
                  disabled={isFormLoading}
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                  disabled={isFormLoading}
                >
                  {isFormLoading ? (
                    <>
                      <LoadingSpinner size="small" />
                      <span>{editingExam ? "Updating..." : "Adding Exam..."}</span>
                    </>
                  ) : (
                    <>
                      <FaSave className="w-4 h-4" />
                      <span>{editingExam ? "Update Exam" : "Add Exam"}</span>
                    </>
                  )}
                </button>
              </div>
            </form>
          </div>
        )}

        {/* Content Area */}
        <div className="bg-white rounded-lg border border-gray-200 overflow-hidden shadow-sm">
          <div className="px-4 py-3 border-b border-gray-200 bg-gray-50">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div>
                <h2 className="text-xl font-semibold text-gray-900">
                  Exams List
                </h2>
                <p className="text-sm text-gray-600 mt-1">
                  Manage your exams, view details, and perform actions
                  {isReorderMode && (
                    <span className="ml-1.5 text-blue-600 font-medium">— Drag rows to change order, then click Done to save</span>
                  )}
                </p>
              </div>
              <div className="flex flex-wrap items-center gap-3">
                {canReorder && filteredExams.length > 1 && !searchQuery.trim() && (
                  isReorderMode ? (
                    <button
                      type="button"
                      onClick={handleDoneReorder}
                      disabled={isFormLoading}
                      className="inline-flex items-center gap-2 px-3 py-1.5 bg-green-600 hover:bg-green-700 text-white rounded-lg text-sm font-medium transition-colors disabled:opacity-50"
                      title="Save order and exit reorder mode"
                    >
                      {isFormLoading ? (
                        <>
                          <LoadingSpinner size="small" />
                          Saving...
                        </>
                      ) : (
                        <>
                          <FaCheck className="w-4 h-4" />
                          Done
                        </>
                      )}
                    </button>
                  ) : (
                    <button
                      type="button"
                      onClick={() => { setIsReorderMode(true); setReorderDraft(null); }}
                      className="inline-flex items-center gap-2 px-3 py-1.5 bg-gray-500 hover:bg-gray-600 text-white rounded-lg text-sm font-medium transition-colors"
                      title="Enable drag and drop to reorder exams"
                    >
                      <FaGripVertical className="w-4 h-4" />
                      Reorder position
                    </button>
                  )
                )}
                {/* Search Input */}
                <div className="relative min-w-[200px] sm:min-w-[240px]">
                  <input
                    type="text"
                    value={searchQuery}
                    onChange={(e) =>
                      setFilterState({ searchQuery: e.target.value, page: 1 })
                    }
                    placeholder="Search exams..."
                    className="w-full pl-9 pr-8 py-1.5 bg-white border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                  />
                  <FaSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 w-3.5 h-3.5" />
                  {searchQuery && (
                    <button
                      onClick={() =>
                        setFilterState({ searchQuery: "", page: 1 })
                      }
                      className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 transition-colors"
                    >
                      <FaTimes className="w-3 h-3" />
                    </button>
                  )}
                </div>

                <div className="flex items-center gap-2">
                  <label className="text-[10px] font-bold text-gray-400 uppercase tracking-wider whitespace-nowrap">Meta Status:</label>
                  <select
                    value={metaFilter}
                    onChange={(e) =>
                      setFilterState({ metaFilter: e.target.value, page: 1 })
                    }
                    className="px-3 py-1.5 bg-white border border-gray-200 rounded-lg text-xs font-medium focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                  >
                    <option value="all">All Items</option>
                    <option value="filled">Meta Filled</option>
                    <option value="notFilled">Meta Not Filled</option>
                  </select>
                </div>
              </div>
            </div>
          </div>

          <div className="p-2">
            {isDataLoading ? (
              <div className="flex items-center justify-center py-12">
                <div className="text-center">
                  <LoadingSpinner size="medium" />
                  <p className="text-sm text-gray-500 mt-3">Loading exams...</p>
                </div>
              </div>
            ) : filteredExams.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-12 text-center">
                <div className="p-4 bg-gray-100 rounded-full mb-4">
                  <FaClipboardList className="w-8 h-8 text-gray-400" />
                </div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">
                  No Exams Found
                </h3>
                <p className="text-sm text-gray-500 mb-4 max-w-sm">
                  {searchQuery
                    ? "No exams match your search criteria."
                    : "You haven't created any exams yet. Click the \"Add New Exam\" button to get started."}
                </p>
                {searchQuery ? (
                  <button
                    onClick={() => setFilterState({ searchQuery: "", page: 1 })}
                    className="px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm font-medium transition-colors"
                  >
                    Clear Search
                  </button>
                ) : canCreate ? (
                  <button
                    onClick={() => setShowAddForm(true)}
                    className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg text-sm font-semibold transition-all duration-200 flex items-center gap-2"
                  >
                    <FaPlus className="w-4 h-4" />
                    Create Your First Exam
                  </button>
                ) : (
                  <div className="px-4 py-2 bg-gray-100 text-gray-500 rounded-lg text-sm font-medium flex items-center gap-2">
                    <FaLock className="w-4 h-4" />
                    <span>{getPermissionMessage("create", role)}</span>
                  </div>
                )}
              </div>
            ) : (
              <>
                <ExamTable
                  exams={filteredExams}
                  onEdit={handleEditExam}
                  onDelete={handleDeleteExam}
                  onToggleStatus={handleToggleStatus}
                  onManageInfo={handleManageInfo}
                  onReorderDraft={handleReorderDraft}
                  reorderDraft={reorderDraft}
                  isReorderAllowed={isReorderMode && !searchQuery.trim()}
                />
                {/* Pagination */}
                {(pagination.totalPages > 0 || pagination.total > 0) && (
                  <PaginationBar
                    page={page}
                    limit={limit}
                    total={pagination.total}
                    totalPages={pagination.totalPages}
                    hasNextPage={pagination.hasNextPage}
                    hasPrevPage={pagination.hasPrevPage}
                    onPageChange={(p) => setFilterState({ page: p })}
                    onLimitChange={(l) => setFilterState({ limit: l, page: 1 })}
                  />
                )}
              </>
            )}
          </div>
        </div>
      </div>
    </>
  );
};

export default ExamManagement;
